name:                test-mongo
version:             0.1.0.0
github:              "why-not-try-calmer/test-mongo"
license:             BSD3
author:              "Adrien Glauser"
maintainer:          "adrien.glauser@gmail.com"
copyright:           "2022 Adrien Glauser"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/why-not-try-calmer/test-mongo#readme>

dependencies:
- base >= 4.7 && < 5
- mongoDB
- text
- hspec

library:
  source-dirs: src

executables:
  test-mongo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - test-mongo

tests:
  test-mongo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - test-mongo
    - hspec